apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: guestbook-test
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 80
  selector:
    app: guestbook-test
    tier: frontend
